
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Mon Sep 25 23:54:53 ART 2023
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "getTipoServicios", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTipoServicios", namespace = "http://ws.das.ubp.edu.ar/")

public class GetTipoServicios {


}

